services:
  - type: worker
    name: telegram-auto-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    disk:
      name: bot-session
      mountPath: /data
      sizeGB: 1
